AWSTemplateFormatVersion: 2010-09-09
Description: CDN

Parameters:
  HostedZone:
    Type: AWS::Route53::HostedZone::Id

  DomainName:
    Type: String

  CertificateArn:
    Type: String

  FrontendBucketRegionalDomainName:
    Type: String

  CloudFrontIdentity:
    Type: String

  LoadBalancerDNSName:
    Type: String

  CDNHeaderValue:
    Type: String

Mappings:
  WAF:
    BlockLists:
      OFACCountryCodes:
        - CU
        - IR
        - KP
        - SY
        - UA
        - RU

Resources:
  CloudfrontRoute53Record:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZone
      RecordSets:
        - Name: !Ref DomainName
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt CloudfrontDistribution.DomainName

  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 0
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        Restrictions:
          GeoRestriction:
            RestrictionType: blacklist
            Locations: !FindInMap [WAF, BlockLists, OFACCountryCodes]
        Origins:
          - Id: StaticAssets
            DomainName: !Ref FrontendBucketRegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontIdentity}
          - Id: ALB
            DomainName: !Ref LoadBalancerDNSName
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
              OriginReadTimeout: 30
              OriginKeepaliveTimeout: 5
            OriginCustomHeaders:
              - HeaderName: X-CDN-TO-ALB
                HeaderValue: !Ref CDNHeaderValue
        Enabled: true
        HttpVersion: http2
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: StaticAssets
          AllowedMethods:
            - GET
            - OPTIONS
            - HEAD
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          ResponseHeadersPolicyId: !Ref ResponseHeadersPolicy
          ViewerProtocolPolicy: redirect-to-https
        CacheBehaviors:
          - PathPattern: /api/*
            AllowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
              - OPTIONS
            Compress: true
            TargetOriginId: ALB
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            ViewerProtocolPolicy: redirect-to-https
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  ResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Ref AWS::StackName
        CorsConfig:
          AccessControlAllowCredentials: false
          AccessControlAllowHeaders:
            Items:
              - "*"
          AccessControlAllowMethods:
            Items:
              - ALL
          AccessControlAllowOrigins:
            Items:
              - !Sub https://${DomainName}
          OriginOverride: false
        CustomHeadersConfig:
          Items:
            - Header: X-Robots-Tag
              Override: true
              Value: noindex
        SecurityHeadersConfig:
          ContentTypeOptions:
            Override: false
          FrameOptions:
            FrameOption: DENY
            Override: false
          ReferrerPolicy:
            ReferrerPolicy: strict-origin
            Override: false
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 63072000
            IncludeSubdomains: true
            Preload: true
            Override: false
          XSSProtection:
            ModeBlock: true
            Protection: true
            Override: false
