[profile.default]
src = "src"
out = "out"
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
remappings = [
    "forge-std/=lib/forge-std/src/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@bobanetwork/aa-hc-sdk-contracts/=node_modules/@bobanetwork/aa-hc-sdk-contracts",
    "hardhat/=node_modules/hardhat/"
]

