name: Daily Python Script

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        working-directory: backend/auto-submit
        run: python run-all.py
        env:
          OC_HYBRID_ACCOUNT: "0x77fbd8f873e9361241161de136ad47883722b971"
          ENTRY_POINTS: "0x0000000071727De22E5E9d8BAf0edAc6f37da032"
          CHAIN_ID: "28882"
          HC_HELPER_ADDR: "0x11c4DbbaC4A0A47a7c76b5603bc219c5dAe752D6"
          OC_LISTEN_PORT: "1234"
          PRE_SIM_TOKEN_ADDR: "0xe7acf278fca7ca33c3ff14da3540b9d2b9a49b90"
          OC_OWNER: "0x4B063eF8d8a6d441d56903c9b4130E79E6099383"
          STARTING_BLOCK: "0"
          BUNDLER_RPC: "https://bundler-hc.sepolia.boba.network"
          BUNDLER_ADDR: "0xe7003B2d8477518DfAE9afB3Bfd6Fe7726A9C551"
          NODE_HTTP: "https://sepolia.boba.network"
          CLIENT_OWNER: "0x4B063eF8d8a6d441d56903c9b4130E79E6099383"
          CLIENT_ADDR: "0x621F17E6d075d21f7a69b1d180b207CA6FEFE4c3"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OC_PRIVKEY: ${{ secrets.OC_PRIVKEY }}
          SUBMITTER_PK1: ${{ secrets.SUBMITTER_PK1 }}
          SUBMITTER_PK2: ${{ secrets.SUBMITTER_PK2 }}
          SUBMITTER_PK3: ${{ secrets.SUBMITTER_PK3 }}
          CLIENT_PRIVKEY: ${{ secrets.CLIENT_PRIVKEY }}